version: '3.8'

services:
  bot:
    build: .
    container_name: mythic-plus-bot
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
    restart: unless-stopped
