name: CI

on:
  pull_request:
    branches: [main, master]
  workflow_call:

jobs:
  lint:
    name: CI
    uses: TytaniumOrg/.github/.github/workflows/lint.yml@main

  build:
    name: CI
    uses: TytaniumOrg/.github/.github/workflows/build.yml@main

  test:
    name: CI
    uses: TytaniumOrg/.github/.github/workflows/test.yml@main
