name: Deploy Activity to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Load Doppler secrets
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: ./scripts/load-doppler-activity-secrets.sh

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: ./setup.sh --skip-verify

      - name: Build Activity
        env:
          VITE_DISCORD_CLIENT_ID: ${{ env.DISCORD_APPLICATION_ID }}
          VITE_SENTRY_DSN: ${{ env.VITE_SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ env.SENTRY_AUTH_TOKEN }}
        run: npm -w activity run build

      - name: Build Storybook
        run: npm -w activity run build-storybook -- -o dist/storybook

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'activity/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
